### PR TITLE
Stop calling deprecated methods on Net::OpenID::Server

### PR DESCRIPTION
**Pull request by oalders**
Fixes https://rt.cpan.org/Ticket/Display.html?id=114044

### CODE REVIEW

**Comment by oalders** [comment]
This does _not_ fix the pre-existing test failure:

```
not ok 5 - verified OpenID

#   Failed test 'verified OpenID'
#   at t/consumer.t line 14.
# no_identity_server: Could not determine ID provider from URL.
```

**Comment by tsibley** [comment]
BPS folks: Happy to do the CPAN release for @oalders if that's OK by you.  /cc @sartak

**Comment by sartak** [comment]
Please do! Thanks @tsibley

**Comment by tsibley** [comment]
@oalders I get this failure after merging your patch:

```
tom@whaam Test-OpenID-Server (master *>) $ prove -lv t/*.t
t/basics.t .... 
ok 1 - use Test::OpenID::Server;
Test::OpenID::Server: You can connect to your server at http://localhost:10792/
ok 2 - start server
ok 3 - use Test::WWW::Mechanize;
ok 4 - fetch non-identity page
ok 5 - got non-identity page
ok 6 - doesn't include server URL
ok 7 - fetch identity page
ok 8 - got identity page
ok 9 - contains correct server URL
ok 10 - fetch openid server endpoint
ok 11 - got openid server endpoint
ok 12 - no (unexpected) warnings (via done_testing)
1..12
ok 2 - no (unexpected) warnings (via END block)
All 12 subtests passed 
t/consumer.t .. 
1..6
ok 1 - use Test::OpenID::Server;
Test::OpenID::Server: You can connect to your server at http://localhost:10703/
ok 2 - started server
ok 3 - use Test::OpenID::Consumer;
Test::OpenID::Consumer: You can connect to your server at http://localhost:14381/
ok 4 - started consumer
ok 5 - verified OpenID
ok 6 - invalid OpenID
ok
t/run.t ....... 
ok 1 - use Test::OpenID::Server;
Test::OpenID::Server: You can connect to your server at http://localhost:14202/
ok 2 - start up my web server
1..2
ok

Test Summary Report
-------------------
t/basics.t  (Wstat: 0 Tests: 13 Failed: 1)
  Failed test:  2
  Parse errors: Plan (1..12) must be at the beginning or end of the TAP output
                Tests out of sequence.  Found (2) but expected (13)
                Bad plan.  You planned 12 tests but ran 13.
Files=3, Tests=21,  1 wallclock secs ( 0.03 usr  0.00 sys +  0.67 cusr  0.07 csys =  0.77 CPU)
Result: FAIL
```

**Comment by tsibley** [comment]
```
tom@whaam Test-OpenID-Consumer (master=) $ perl -MV=Test::Warnings
Test::Warnings
    /opt/perlbrew/perls/5.20/lib/site_perl/5.20.1/Test/Warnings.pm: 0.026
tom@whaam Test-OpenID-Consumer (master=) $ perl -MV=Test::More
Test::More
    /opt/perlbrew/perls/5.20/lib/site_perl/5.20.1/Test/More.pm: 1.302052
    /opt/perlbrew/perls/5.20/lib/5.20.1/Test/More.pm: 1.001002
```

**Comment by tsibley** [comment]
@oalders Since Github didn't notify me last time about activity on this thread, please feel free to highlight me in #metacpan.

**Comment by tsibley** [comment]
Fixed myself and released version 0.03 to CPAN just now.  See also PR #2 for my changes.

**Pull request merged**
